export const servicesData = [
  {
    id: 'bridal',
    tag: 'Bridal',
    title: 'Bridal Artistry',
    title_zh: '新娘化妆艺术',
    price: 'Starts RM 1,200',
    price_zh: '起价 RM 1,200',
    description: 'A comprehensive luxury experience tailored for your wedding day. Includes a pre-wedding trial, premium skin prep, long-lasting makeup application, and touch-up kit.',
    description_zh: '为您的婚礼量身定制的全面奢华体验。包括婚前试妆、高级妆前护肤、持久化妆和补妆包。',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCYV3ptJG-8gouAn8ivF0GfprlC-4NVNizWkyvHlvT1WGOB7zDsME6leB1SugUfvpACuHIv1RPIMvop-a5rxcmqmY53LprLr0gpisyG_3FchAFbyTX658LkGCic1jyoLsgU_SeDTzNOP-VigX51T-hg_IdVCQmyM8o06XCh8k9ACEeLGaRFKtkxfzDwciLoJfc7OGXp23P-fdDpG72n5UMw8LIblnj2gWvUKC-Nh_quRNz9WBuB5IOP-vv8oDEbtmZzaORWd_CWzw',
  },
  {
    id: 'dinner-gala',
    tag: 'Event',
    title: 'Dinner & Gala',
    title_zh: '晚宴与盛会',
    price: 'Starts RM 450',
    price_zh: '起价 RM 450',
    description: 'Make an entrance with sophisticated evening glam. Custom looks ranging from soft, luminous skin to bold, dramatic eyes designed specifically for event lighting.',
    description_zh: '以精致的晚间魅力惊艳全场。从柔和、发光的肌肤到大胆、引人注目的眼妆，专为活动照明设计。',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAqGbpH0A8LPDx40IYFj1YEvZ3U36tNtoLr379cQnMkQi2L8IOLAlhLoj1KjI_xHNF8J25E_yP0JCQ_T8QyldziTj7IgiX9ZHWnrd8wdJ_5OdtrlgIVqvf26RssiJuHbpIxzMefA8RC9R1q-WP-pNOTxkBNdVtpenYvO2MeQwu3SurorLDzg95856nlTtwGaZt14Gl90k34yHUKM6ynOd5Sz0IoDQIDcCLuhGg5Hse0-Yw4iyGi-kpGO6YVKDVnokRso1kCWjcejQ',
  },
  {
    id: 'special-effects',
    tag: 'Creative',
    title: 'Special Effects',
    title_zh: '特效化妆',
    price: 'Custom Quote',
    price_zh: '定制报价',
    description: 'Advanced prosthetic application and character creation for film, theater, or themed events. Requires consultation for accurate pricing.',
    description_zh: '用于电影、戏剧或主题活动的高级假肢应用和角色创建。需要咨询以获得准确的定价。',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuChZuhA_OmUWp0n_lLhUrFAAyPWs5evqkDZLnF3xfm4cnBtGqY-6dbltg4fENuu3Q_nZci9NoHoP6lRNFzuqUkzY94l07O5oueFUxlsk4lkA0ouLYzAS2tU8KfGd3MlgE4FenRvo_FMtUrMAguFJABpab_Ltx-PE3umWjtJHb6GFmZfd3_8mOIUasIOiKz5TTH-MVGobEoQ5f6NQpffPsLEqzU4IomEEZx9HelK2tvfTf1Hlu2B4pDfLgo8ZKo98HJ22S2BO2i9Tg',
  },
  {
    id: 'photoshoot',
    tag: 'Editorial',
    title: 'Photoshoot',
    title_zh: '照片拍摄',
    price: 'Starts RM 600',
    price_zh: '起价 RM 600',
    description: 'Camera-ready makeup for commercial, fashion, or personal branding shoots. Includes half-day or full-day on-set standby options.',
    description_zh: '为商业、时尚或个人品牌拍摄准备的镜头感化妆。包括半天或全天现场待命选项。',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAWrMnm59ZjVovfzt2X0W3n1aIW8msLK7mCl7JwEDPs-R_BI_U5AJwEzHpyg5IEgsjqM0RHR83FegQeozYrS3IsVnWi7t1hyCL_UnvrbDreWfz1CNsJ0uPnSmtQFzGZSbcEGe53YXnD7sqF24lMMmFyLRx7X9cSJCrM8Ir4kIcQfEh6E8HvXy6X2D5T80CLiWO9CsxO3fSFR1_tz5XgGEf3y_bQlZa2jFXvd9CD0Cpl_2nS-JBqhuJJX055qkaIj9vf7--RW2QLCg',
  }
];
